spring:
  application:
    name: config-default
springdoc:
  packages-to-scan: 'link.grooverdev.web.api.userservice.controller'
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %p %c{1.} [%t] %m%n"
  level:
    org.springframework.web: ERROR
    link.grooverdev.web.api.userservice: DEBUG
    org.hibernate: ERROR
  file:
    name: app-microservice.log
server:
  port: ${PORT:0}
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
